name: 'Comment on new issue'
description: 'Comment on issue with a defined message whenever someone creates a new issue.'
author: jd-0001
branding:
  icon: file-text
  color: purple
inputs:
  token:
    description: "GitHub personal token"
    required: false
    default: ${{ github.token }}
  message:
    description: 'Comment Content'
    required: true
  ignore-label:
    description: 'Ignore commenting when this label is found on the issue.'
    required: false
  only-if-label:
    description: 'Only post comment if this label is found on the issue.'
    required: false
  raise-support-using-form-msg:
    description: "Message to send before closing issue if issue isn't created using support form"
    required: true
  debug:
    description: "Debug the action which will print more information on how its running and what's processing"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'